name: Build Docker images

on:
  push:
    branches: master
jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build base image
        run: |
          ./build.sh -i gnuradio-base -r ${{ github.event.before }}..${{ github.sha }}
  build-gnuradio-amd64:
    runs-on: ubuntu-latest
    needs: build-base
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - name: install buildx
      #   id: buildx
      #   uses: crazy-max/ghaction-docker-buildx@v1
      #   with:
      #     version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build gnuradio image
        run: |
          ./build.sh -i gnuradio -r ${{ github.event.before }}..${{ github.sha }} -p linux/amd64
  build-gnuradio-arm:
    runs-on: ubuntu-latest
    needs: build-base
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - name: install buildx
      #   id: buildx
      #   uses: crazy-max/ghaction-docker-buildx@v1
      #   with:
      #     version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build gnuradio image
        run: |
          ./build.sh -i gnuradio -r ${{ github.event.before }}..${{ github.sha }} -p linux/arm
  build-gnuradio-arm64:
    runs-on: ubuntu-latest
    needs: build-base
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - name: install buildx
      #   id: buildx
      #   uses: crazy-max/ghaction-docker-buildx@v1
      #   with:
      #     version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build gnuradio image
        run: |
          ./build.sh -i gnuradio -r ${{ github.event.before }}..${{ github.sha }} -p linux/arm64
  build-gnuradio-manifest:
    runs-on: ubuntu-latest
    needs: [build-gnuradio-amd64,build-gnuradio-arm,build-gnuradio-arm64]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build gnuradio manifest
        run: |
          DOCKER_CLI_EXPERIMENTAL=enabled ./build.sh -i gnuradio -r ${{ github.event.before }}..${{ github.sha }} -f -m -p linux/amd64,linux/arm,linux/arm64